---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./envoy-gateway/ks.yaml
  - ./envoy-gateway/ks-gateway.yaml
  - ./envoy-gateway/ks-referencegrant.yaml
  - ./reloader/ks.yaml
