---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager/ks.yaml
  - ./cert-manager/ks-rbac.yaml
  - ./cert-manager/issuers/ks.yaml
  - ./trust-manager/ks.yaml
  - ./trust-manager/ks-bundle.yaml
  - ./vault/ks.yaml
