# Secret containing the provisioner password for step-ca
apiVersion: v1
kind: Secret
metadata:
    name: step-ca-provisioner
    namespace: cert-manager
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:xyUO1CV7FQi+xdBr5QyZ+NArn1aVFKlXteqUTsj5cPQ=,iv:2srW1CK6QEC9gTJg+5DL2cbhVpn26w1rrmo6wAsWwzI=,tag:yrbHDEWdgJ5SAnj0V0lm3g==,type:str]
sops:
    age:
        - recipient: age145240rs7s8y8e5tvz747ccxj9504hqhvrw4m5zy8y9zc9sjarpcq6ptf98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvL2VLdmJ5NUNvcG9uOXA0
            QW1hckNiZDc0N3BkZnJLMXFEMlo3SEJaY0hvCnpTRytoU3dWNGZUTGV4WEdlTFp3
            Zlhocnl1anc2WDRWbDRhM3htVnByNlkKLS0tIDEvdlBXa3djbkRCd1IxWjY0NVZt
            Z2pscEl1TG8vU1YzYVFSQVhLckplYzAK945e5lXCKkJ7RecGS2JpRI7Z6+gbr6li
            IN5gdOWXcx6u2m/o/asy6S8gem6Hrw7MCYH7Bj4oaBRj5+KpRkhH/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T23:20:15Z"
    mac: ENC[AES256_GCM,data:T1zR3j5Azsck0S6LvW1ntsqE+P377N/fvjgttk+8Vinv+f6dVLHep2GxGp5KUknYbnrJx2w9IB9VHHBCCyFsWE6sOk/rgNFDvRqe2F+9Do4Yf+5t1W3OlVpFL805s6wbtwdzwge8nUJowH57itaAXi0x3h00a4OmAV+H/QcTcD4=,iv:WypfRi499gtMWFD0fgwakqGP+L9nqxBOP8tG1XWPDas=,tag:NffZNEEm9RU8wun46dYmJg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
