---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./istio-gateway/ks.yaml
  - ./cilium/ks.yaml
  # kube-proxy disabled - using Cilium kube-proxy replacement instead
  # - ./kube-proxy/ks.yaml
