---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./gateway.yaml
  - ./referencegrant-httproutes.yaml
  - ../resources/envoyfilter-oauth2.yaml
  - ../resources/envoyfilter-oauth2-bypass.yaml
