---
apiVersion: v1
kind: Secret
metadata:
  name: democratic-csi-webdav-rclone-config
  namespace: storage
type: Opaque
stringData:
  rclone.conf: |
    [decypharr]
    type = webdav
    url = http://decypharr.default.svc.cluster.local:8282/webdav/realdebrid
    vendor = other
