---
# AuthorizationPolicy to bypass ext_authz for specific public apps
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: public-apps-bypass
  namespace: media
spec:
  selector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: media-gateway-istio
  action: ALLOW
  rules:
    - to:
        - operation:
            hosts: ["plex.chillincool.net"]
