---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: huntarr
  namespace: network
spec:
  interval: 1m
  chart:
    spec:
      chart: huntarr
      version: "0.x.x"
      sourceRef:
        kind: HelmRepository
        name: chillincool
        namespace: flux-system
  install:
    timeout: 10m
    remediation:
      retries: 5
    createNamespace: false
    crds: Create
  upgrade:
    timeout: 10m
    cleanupOnFail: true
    crds: CreateReplace
  values:
    strategy:
      type: Recreate
    httpRoute:
      enabled: true
      parentRefs:
        - name: istio-gateway-internal
          namespace: network
          sectionName: https-huntarr
      hostnames:
        - huntarr.chillincool.net
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - name: huntarr
              port: 5000

    env:
      - name: HUNTARR_PORT
        value: "8080"

    service:
      type: ClusterIP
      port: 5000
      targetPort: http

    podSecurityContext:
      fsGroup: 568

    securityContext:
      runAsNonRoot: true
      runAsUser: 568
      runAsGroup: 568
      readOnlyRootFilesystem: false

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: huntarr-config
        globalMounts:
          - path: /config
