apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-crds
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/infrastructure/keycloak/crds
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
