apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-instance
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/infrastructure/keycloak/instance
  prune: true
  wait: true
  dependsOn:
    - name: keycloak-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
