---
apiVersion: v1
kind: ConfigMap
metadata:
  name: imagemaid-config
  namespace: default
data:
  config.yml: |
    plex:
      url: http://plex:32400
      token: YOUR_PLEX_TOKEN_HERE
    
    # Main settings
    settings:
      mode: show  # Options: show, move, delete
      
    # What to clean
    libraries:
      - Movies
      - TV Shows
    
    # Rules for what gets cleaned
    rules:
      # Remove images for items deleted from Plex
      remove_deleted: true
      
      # Remove duplicate images
      remove_duplicates: true
      
      # Remove unused season posters
      remove_unused_seasons: true
      
      # Remove unused episode thumbnails
      remove_unused_episodes: true
