---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-metrics-stack
  namespace: flux-system
spec:
  dependsOn:
    - name: victoria-metrics-operator
  interval: 30m
  path: ./kubernetes/apps/monitoring/victoria-metrics-stack/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 10m
  targetNamespace: monitoring
