---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main-gateway
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https-radarr
      protocol: HTTPS
      port: 443
      hostname: talos-radarr.chillincool.net
      allowedRoutes:
        namespaces:
          from: Same
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: radarr-tls
    - name: https-suggestarr
      protocol: HTTPS
      port: 443
      hostname: suggestarr.chillincool.net
      allowedRoutes:
        namespaces:
          from: Same
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: suggestarr-tls
    - name: https-huntarr
      protocol: HTTPS
      port: 443
      hostname: huntarr.chillincool.net
      allowedRoutes:
        namespaces:
          from: Same
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: huntarr-tls
    - name: https-sonarr-anime
      protocol: HTTPS
      port: 443
      hostname: sonarr-anime.chillincool.net
      allowedRoutes:
        namespaces:
          from: Same
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: sonarr-anime-tls
