---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: csi-rclone-secret-reader
  namespace: csi-rclone
rules:
  - apiGroups: [""]
    resources: [secrets]
    verbs: [get, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: csi-rclone-controller-secret-reader
  namespace: csi-rclone
subjects:
  - kind: ServiceAccount
    name: csi-controller-rclone
    namespace: csi-rclone
roleRef:
  kind: Role
  name: csi-rclone-secret-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: csi-rclone-node-secret-reader
  namespace: csi-rclone
subjects:
  - kind: ServiceAccount
    name: csi-nodeplugin-rclone
    namespace: csi-rclone
roleRef:
  kind: Role
  name: csi-rclone-secret-reader
  apiGroup: rbac.authorization.k8s.io
