---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./istio-gateway
  - ./waypoint/ks.yaml
  - ./authz-policy
  - ./shared-config-pvc.yaml
  - ./backups-pvc.yaml
  - ./dsm1-anime-pv.yaml
  - ./dsm1-data-pv.yaml
  - ./config-manager-pod.yaml
  - ./realdebrid-rclone-secret-copy.yaml
  - ./decypharr/ks.yaml
  - ./decypharr/enable/ks.yaml
  - ./huntarr/ks.yaml
  - ./imagemaid/ks.yaml
  - ./kometa/ks.yaml
  - ./lidarr/ks.yaml
  - ./overseerr/ks.yaml
  - ./plex/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./radarr-4k/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./sonarr-4k/ks.yaml
  - ./sonarr-anime/ks.yaml
  - ./suggestarr/ks.yaml
  - ./tautulli/ks.yaml
  - ./symlinks-pvc.yaml
  - ./onepassworditem.yaml
