---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: radarr-secret
  namespace: media
spec:
  itemPath: "vaults/talos/items/radarr-secret"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: radarr-4k-secret
  namespace: media
spec:
  itemPath: "vaults/talos/items/radarr-4k-secret"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: sonarr-secret
  namespace: media
spec:
  itemPath: "vaults/talos/items/sonarr-secret"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: sonarr-4k-secret
  namespace: media
spec:
  itemPath: "vaults/talos/items/sonarr-4k-secret"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: sonarr-anime-secret
  namespace: media
spec:
  itemPath: "vaults/talos/items/sonarr-anime-secret"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: lidarr-secret
  namespace: media
spec:
  itemPath: "vaults/talos/items/lidarr-secret"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: prowlarr-secret
  namespace: media
spec:
  itemPath: "vaults/talos/items/prowlarr-secret"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: decypharr-auth
  namespace: media
spec:
  itemPath: "vaults/talos/items/decypharr-auth"
