---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rclone-realdebrid
provisioner: csi-rclone
parameters:
  remote: decypharr
  remotePath: /realdebrid
  csi.storage.k8s.io/provisioner-secret-name: rclone-secret-realdebrid
  csi.storage.k8s.io/provisioner-secret-namespace: csi-rclone
  csi.storage.k8s.io/controller-publish-secret-name: rclone-secret-realdebrid
  csi.storage.k8s.io/controller-publish-secret-namespace: csi-rclone
  csi.storage.k8s.io/node-stage-secret-name: rclone-secret-realdebrid
  csi.storage.k8s.io/node-stage-secret-namespace: csi-rclone
  csi.storage.k8s.io/node-publish-secret-name: rclone-secret-realdebrid
  csi.storage.k8s.io/node-publish-secret-namespace: csi-rclone
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: realdebrid-webdav
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rclone-realdebrid
  volumeName: realdebrid-webdav-manual
  resources:
    requests:
      storage: 100Gi
