---
apiVersion: v1
kind: Secret
metadata:
  name: rclone-secret-realdebrid
  namespace: csi-rclone
type: Opaque
stringData:
  remote: decypharr
  remotePath: /realdebrid
  configData: |
    [decypharr]
    type = webdav
    url = http://decypharr.default.svc.cluster.local:8282/webdav
    vendor = other
