---
# yaml-language-server: $schema=https://kubernetes-schemas-cvg.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chillincool-net
spec:
  secretName: chillincool-net-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: chillincool.net
  dnsNames:
    - chillincool.net
    - "*.chillincool.net"
