---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: suggestarr
  namespace: default
spec:
  parentRefs:
    - name: main-gateway
      namespace: default
      sectionName: https-suggestarr
  hostnames:
    - "suggestarr.chillincool.net"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: suggestarr
          port: 3000
