---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak

resources:
  - ./namespace.yaml
  - ./referencegrant.yaml
  - ./keycloak/ks.yaml
  - ./redis/ks.yaml
  - ./oauth2-proxy/ks.yaml
