apiVersion: v1
data:
    token: ENC[AES256_GCM,data:OnbctkSZ7T/yXx3ZLkk4ynAW7qPVU7HbVtDcPsOrV8UO4BgcfIO6SaMJ9MqO6rnahcIs7adVJmUxCGyONxouGphkBn1TEsvCNyxVFEZXUngWcwSNbyqhKBZpgLsrmK85AH5BLZKl5QGptIsWBVnchhvoAgbTFjUE+sOUiLTy6ncA046HQW755kevTtdmiy+o9u4Ytjsfdl2Rx7g6Yb2qs/1c2HEDF20kyuZ5dfA4KWIFH5h3GkaDg/H2UEUHJOEkyS9X/N978j/AWD42AGbMtG7ZmPH95VAniS7YQCS32UrQNZol8ieOZMg+RkpkyYZcgyEoox229sRuH52kLtEMOAlIPk/Bpg/rqzbIqZUEi/ekM8msjlS/yyHyj2lbKUsDLCDEJudV0HGfSm1PoiOjZCAUBGD6ARKOEzu3uUHsqOnA7m3Sb29TREBCT1NZuB76HjSKgcuSJ0QNqCBHwaWOKhaH6Y1MYFwUvTuUZPjH+wydrJqEfjuWJ3L4RxSO3j7Av5xBW+t0LYfphiGiw7IZP6J1msuvVWZs5PN6kUMyVTA4S95Sy9ESJlTSB7v8yix3S2TPythbenApAptmC/XdvBdsts9oRMDW7hFM3S7kVyxYZ+tviOp2aWZ2rJsewX0dBn4WSkTgaf+9LzQp9/tRPu1yvRr7u7Gevj6flkTPYS45k6UlJpDynKNbH3A5LceEx+dCy65snn7m2pd8f6L5lFCZqMd8hkfQNLpnaIi483fP+/pS+2mhuSCnnQ6+HP1gcQRYBMaF3QhPN6NtUgPw0LL00KURXyxfTOSbVyeOPexM/95ZUE8OfzdTp5M1MDqjdfGUX/lnpzGgCowDFjYpa64GW/4TTRqodEwWkqmVgyD+RI0KJ+liGW1quXg7D1ibCnObvlLiTF1w9XaMW5nnhQlksI5PQ9XSL9p6RHJXgTlUBeA0+NShfIAwrh3JP0XRPquTzdpPUNxAwqWKN6N9+Jj2jYyIyLVRD+IqJz21PL06Kp1oyGn/DKjF2413++rr42vA++WBE1SfK+omwr6voiekVRbLoZKaGp8mVHwI+2R9mImv+KTGvaVx3apokm5fVY9oWVLZw3IxZUYA6BsRRDCdqFNk6nkgYHAj8eDNXDyRm+tFJQKT0A==,iv:WNBHRGxH8XXa3CNz+3x138k6C0H1SEz+sks3a0ymzbs=,tag:mMOvsOSBa5Hsv4+C9g1nJg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: onepassword-token
    namespace: onepassword
sops:
    age:
        - recipient: age145240rs7s8y8e5tvz747ccxj9504hqhvrw4m5zy8y9zc9sjarpcq6ptf98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWEtaeVJLR09UYUdibzlm
            U3NIanliVGp4OGtid08yMWNNOTJsbWx0NURNCk93Qk8weVY3SUdOMUNnWUg1dkQ4
            YUQvdGhSTW1BN1FEdWpLb2xnNmtLVmsKLS0tIFUyMDRhdWlaelNkaldsQ0RaMnY2
            K0poT2ZtUGkwZ2gvcnVSWVZOKzJRSk0KbkHS38X0AlSHXCK/gtQe3CuEla7cXieF
            XqU/bXOxvnLXJlMEKdQSqYAd0XpE6xw01QgrTrzsyJVO1dEUj71MpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T02:14:02Z"
    mac: ENC[AES256_GCM,data:AvgQPfSNYTtx/SNPjjL07enks937LmSD1vj5ReQnY2cYwi5iGfmpjA9jkf91cPKZNvWMpnOw6tF1R5Fxf+cAbbPIsfWGagOEdyeW4yTzYvzaIWy1jnib0g79ihkI9WJSm8SWGXVDOdOu0K79E1hJ3Y9jmhcy/lkQzeDFOuU7tZc=,iv:3K7yd94hqGJb+qM28mOzuBtirDZyHuGIfRJkFUhFVVg=,tag:KJ4fRn8LcKNchE5sDji/tA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
