apiVersion: v1
data:
    onepassword-token: ENC[AES256_GCM,data:5QnjhHpRgOaCvRVwVu8qv3PmBLxGfGdte1AGPYKuPmex37b3mwldUgx+1E+nhOb88kSNceF6qsGFIP5XaoE42yNlqUvn4ZF1p/XXvqBfrOtha3Fo0f7iaMBX3H8FlwZCmH6HhmTyOVDEMypM0KMBnsPTMone7IYz3gEkocj0iXFGqPKWNt3F8pxn5aQWylGk4rHJ900cOC8AeCfCcmLxRQoDn7LKtlK27O+3I/dcbGOPOjwEJJrlFREEuTIYbCunm3YIsC3jqgpIW/DLFjQn7neIShaThWE+RQLHntWlYXMLdxQj5tcReHAMPnQqIyimxDMtv35z4JAASBTy9fGKDY+QeeuOk7D/5HlAR9vue6SQlf4X8QiM8A6lWnm7NKdmsJZZnCVBX3CgVJQhvJeoF5RxxlZm63HyiPrr+NYtTT0fcaWtaLxah8kLAthgpOWJz/qFYwb+ttar6hseuV/o4M/tlexf+y2kV370qKIRv68Nl2VPKP3qwUWZxEaqyXPdaDD2zZbHkKrvhQ8Pw2/iSyGXA464KQmKDxuVXFjDmBUUZhOK9QdUC8j8hb3a9TzqTmLSHR0MDFtNdn1mGpeHuedvm6qzH6EKhy6g6w/8iPeUeIdK+c5jpoRT91SQfPhRlihQRhFSVw3tGfFDabLV/oGzuK5Hz35HQAcHBaGhGvzDqFWancQuXEAsVlZO6CKFTff9dUcQgwoBeySehRkxi3qFj496l3wtRdMdaVtH/VAjvP5m+F7e6DsRqjygzXvS049OHYA4QlkTBE+IBhyLVWDpdPqZpATDbTCwqLLPrlAojz/YnDXBCtLTVkuZ10z/DrMMoIiTs3GYh6NbEFiuxHLcVZ88zBJMY8ngHGf/cTXPdCTHyisCWklvI0rme7gcabXf34/RCgQK9qeJ8H8dgXtaWR5p0XpGQuR83PHsHJLXRFTCzh/IWaAzmS3hgrxbpV4egsgpdgHZjsc72tM/PE+Q6X3VR5+WxaU1+agDFUl5XLdWQ/D99qYaeauS79548Bo1b996VzxRNqEJI0J+5ChsL3od8fCkLSVB1ccI7u2CP14fOdb0ANg6x5jAS9gYeytH2Vdm2ZwEwhwtohiVwqbwfrdXP2GcXLWdN8u0u+LESdF7C4pmGQ==,iv:cgwshmpUNoAjlzwas3uclEY6OmXDtMCTw3KHtjzin9E=,tag:in3MFfOLe1UIqZba19K7gA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: token
    namespace: onepassword
sops:
    age:
        - recipient: age145240rs7s8y8e5tvz747ccxj9504hqhvrw4m5zy8y9zc9sjarpcq6ptf98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOS3d1TlBXZWRJUDZaMGhN
            Y1ZHdHMyeXpKbjBpSTZtcUdJbEJNZ2I2bWwwCmZlVllFbkxpcEhHUmRMREtjZmlt
            UnNBWjk1QkRYaFpiTkVzUDh6SGxwK2MKLS0tIDRpYlNOTUFqclY3UEEvMnowUG55
            TFowbXoyYlRuUXZHYXFoSXVmbEx0UXcKKZbsbCTYqE18CTtwiBVUL1H+AFTBOyCO
            sSw+KH+jF+fCaIcUWb6TSwth7/RSOSeRHWuoWRFi6onCV/LHGiO0/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T03:02:02Z"
    mac: ENC[AES256_GCM,data:W0rVVC7kdO2qEIAJ5ezsXN5j4nGKOK94JjsbY98GCR4s/3kZox8VDvmIxezcXyHE8cdCcE4HiEgqV1mvp8daU8UFzuQr2Rdrd6c+wnehtRNJF/6EXt0QvjJg2ZejODa48e/0x3SBO9JsVBh751fYOJGvpj7sWXK5kedvP1FEubc=,iv:bs+L5HtdFVZWExG7hiPLHDSH2yWZy5i1dHH9nHseWYI=,tag:BE8P46Q6val90C3g6h62Jg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
