---
# yaml-language-server: $schema=https://kubernetes-schemas-cvg.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: plextraktsync
spec:
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  interval: 1h
  path: ./kubernetes/apps/media/plextraktsync/app
  postBuild:
    substitute:
      APP: plextraktsync
      VOLSYNC_CAPACITY: 1Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false
