---
# yaml-language-server: $schema=https://kubernetes-schemas-cvg.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: koel
spec:
  components:
    - ../../../../components/nfs-scaler
    - ../../../../components/volsync
  dependsOn:
    - name: cloudnative-pg
      namespace: cloudnative-pg
    - name: longhorn
      namespace: longhorn-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: koel
      namespace: media
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: koel-db
      namespace: media
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      failed: status.phase == 'Failed'
      current: status.phase == 'Cluster in healthy state'
  interval: 1h
  path: ./kubernetes/apps/media/koel/app
  postBuild:
    substitute:
      APP: koel
      VOLSYNC_CAPACITY: 5Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false
