---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../namespace.yaml
  - ./cert-manager-rbac.yaml
  - ./vault-tls-certificate.yaml
  - ./helmrelease.yaml
  - ./vault-clusterissuer.yaml
