---
# Self-signed issuer for bootstrapping Vault TLS
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-selfsigned
  namespace: vault
spec:
  selfSigned: {}
---
# Bootstrap certificate for Vault internal TLS
# This will be replaced with a Vault-issued certificate later
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: vault
spec:
  secretName: vault-tls
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - chillincool
  commonName: vault.vault.svc.cluster.local
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
    - digital signature
    - key encipherment
  ipAddresses:
    - 127.0.0.1
  dnsNames:
    - vault
    - vault.vault
    - vault.vault.svc
    - vault.vault.svc.cluster.local
    - vault-0.vault-internal
    - vault-0.vault-internal.vault
    - vault-0.vault-internal.vault.svc
    - vault-0.vault-internal.vault.svc.cluster.local
    - vault-1.vault-internal
    - vault-1.vault-internal.vault
    - vault-1.vault-internal.vault.svc
    - vault-1.vault-internal.vault.svc.cluster.local
    - vault-2.vault-internal
    - vault-2.vault-internal.vault
    - vault-2.vault-internal.vault.svc
    - vault-2.vault-internal.vault.svc.cluster.local
    - vault-active
    - vault-active.vault
    - vault-active.vault.svc
    - vault-active.vault.svc.cluster.local
    - vault-standby
    - vault-standby.vault
    - vault-standby.vault.svc
    - vault-standby.vault.svc.cluster.local
  issuerRef:
    name: vault-selfsigned
    kind: Issuer
