---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./gateway/ks.yaml
  - ./referencegrant/ks.yaml
  - ./victoria-metrics-operator/ks.yaml
  - ./victoria-metrics-stack/ks.yaml
  - ./node-exporter/ks.yaml
  - ./grafana/ks.yaml
