---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./istio-gateway/ks.yaml
  - ./waypoint/ks.yaml
  - ./kiali-operator/ks.yaml
  - ./kiali-operator/resources/ks.yaml
  - ./victoria-metrics-k8s-stack/ks.yaml
