---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main-gateway
  namespace: envoy-gateway-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https-radarr
      protocol: HTTPS
      port: 443
      hostname: radarr.chillincool.net
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: radarr-tls
            namespace: media
    - name: https-suggestarr
      protocol: HTTPS
      port: 443
      hostname: suggestarr.chillincool.net
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: suggestarr-tls
            namespace: media
    - name: https-huntarr
      protocol: HTTPS
      port: 443
      hostname: huntarr.chillincool.net
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: media
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: huntarr-tls
            namespace: media
    - name: https-sonarr-anime
      protocol: HTTPS
      port: 443
      hostname: sonarr-anime.chillincool.net
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: media
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: sonarr-anime-tls
            namespace: media
    - name: https-prowlarr
      protocol: HTTPS
      port: 443
      hostname: prowlarr.chillincool.net
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: media
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: prowlarr-tls
            namespace: media
    - name: https-decypharr
      protocol: HTTPS
      port: 443
      hostname: decypharr.chillincool.net
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: media
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: decypharr-tls
            namespace: media
    - name: https-lidarr
      protocol: HTTPS
      port: 443
      hostname: lidarr.chillincool.net
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: media
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: lidarr-tls
            namespace: media
    - name: https-overseerr
      protocol: HTTPS
      port: 443
      hostname: overseerr.chillincool.net
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: media
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: overseerr-tls
            namespace: media
    - name: https-plex
      protocol: HTTPS
      port: 443
      hostname: plex.chillincool.net
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: media
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: plex-tls
            namespace: media
    - name: https-radarr-4k
      protocol: HTTPS
      port: 443
      hostname: radarr-4k.chillincool.net
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: media
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: radarr-4k-tls
            namespace: media
    - name: https-sonarr
      protocol: HTTPS
      port: 443
      hostname: sonarr.chillincool.net
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: media
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: sonarr-tls
            namespace: media
    - name: https-sonarr-4k
      protocol: HTTPS
      port: 443
      hostname: sonarr-4k.chillincool.net
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: media
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: sonarr-4k-tls
            namespace: media
    - name: https-tautulli
      protocol: HTTPS
      port: 443
      hostname: tautulli.chillincool.net
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: media
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: tautulli-tls
            namespace: media
