---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: real-debrid-egress
  namespace: istio-egress
spec:
  targetRefs:
  - kind: ServiceEntry
    group: networking.istio.io
    name: real-debrid-api
  action: ALLOW
  rules:
  - {}
