---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 30m
  chart:
    spec:
      chart: istiod
      version: 1.28.x
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  dependsOn:
    - name: istio-base
    - name: istio-cni
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    profile: ambient

    meshConfig:
      extensionProviders:
        - name: oauth2-proxy
          envoyExtAuthzHttp:
            service: oauth2-proxy.oauth2-proxy.svc.cluster.local
            port: 4180
            pathPrefix: /oauth2/auth
            headersToUpstreamOnAllow:
              - authorization
              - path
              - x-auth-request-user
              - x-auth-request-email
              - x-auth-request-access-token
            headersToDownstreamOnDeny:
              - content-type
              - set-cookie
            includeRequestHeadersInCheck:
              - cookie
              - x-forwarded-access-token
              - x-forwarded-user
              - x-forwarded-email
              - x-forwarded-proto
              - x-forwarded-host
              - x-forwarded-uri

    pilot:
      env:
        PILOT_ENABLE_IP_AUTOALLOCATE: "true"
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 1
          memory: 1Gi
