---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../namespace.yaml
  - ./helmrelease-base.yaml
  - ./helmrelease-cni.yaml
  - ./helmrelease-istiod.yaml
  - ./helmrelease-ztunnel.yaml
  - ../resources/vmservicescrape-istiod.yaml
  - ../resources/vmservicescrape-ztunnel.yaml
  - ../resources/vmpodscrape-waypoint.yaml
