---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: util

components:
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./atuin/ks.yaml
  - ./firefly-iii/ks.yaml
  - ./immich/ks.yaml
  - ./paperless-ngx/ks.yaml
  - ./thelounge/ks.yaml
