---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oauth2-proxy-tls
  namespace: keycloak
spec:
  secretName: oauth2-proxy-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - auth.chillincool.net
