---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - onepassworditem.yaml
  - certificate.yaml
  - helmrelease.yaml
  - gateway.yaml
  - ../ext-authz/authorizationpolicy-oauth2-bypass.yaml
