---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: step-ca
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/apps/infrastructure/step-ca/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 10m
  targetNamespace: step-ca
  decryption:
    provider: sops
    secretRef:
      name: sops-age
