---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfs-csi-driver
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/apps/kube-system/nfs-csi-driver/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 10m
