---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./shared-config-pvc.yaml
  - ./backups-pvc.yaml
  - ./config-manager-pod.yaml
  - ./reloader/ks.yaml
  - ./realdebrid-rclone-secret-copy.yaml
  - ./decypharr/ks.yaml
  - ./decypharr/enable/ks.yaml
  - ./lidarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./tautulli/ks.yaml
  - ./symlinks-pvc.yaml
