---
apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
  namespace: default
type: Opaque
stringData:
  RADARR__APP__INSTANCENAME: "Radarr"
  RADARR__AUTH__APIKEY: "639dd79258ad342bf42f09dbbf78df45"
---
apiVersion: v1
kind: Secret
metadata:
  name: radarr-4k-secret
  namespace: default
type: Opaque
stringData:
  RADARR-4K__APP__INSTANCENAME: "Radarr 4K"
  RADARR-4K__AUTH__APIKEY: "2f0d188d607b2f12eaf7a674b173db3e"
---
apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
  namespace: default
type: Opaque
stringData:
  SONARR__APP__INSTANCENAME: "Sonarr"
  SONARR__AUTH__APIKEY: "b7cef63b8fe52dc96865ce6b3adf236d"
---
apiVersion: v1
kind: Secret
metadata:
  name: sonarr-4k-secret
  namespace: default
type: Opaque
stringData:
  SONARR-4K__APP__INSTANCENAME: "Sonarr 4K"
  SONARR-4K__AUTH__APIKEY: "4b6c572e1bededa9a9cf01f8827077fe"
---
apiVersion: v1
kind: Secret
metadata:
  name: sonarr-anime-secret
  namespace: default
type: Opaque
stringData:
  SONARR-ANIME__APP__INSTANCENAME: "Sonarr Anime"
  SONARR-ANIME__AUTH__APIKEY: "1d6c0a4c4ddee3390729dc57b467b69d"
---
apiVersion: v1
kind: Secret
metadata:
  name: lidarr-secret
  namespace: default
type: Opaque
stringData:
  LIDARR__APP__INSTANCENAME: "Lidarr"
  LIDARR__AUTH__APIKEY: "d67adba7995fe433640bf1851789168e"
---
apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-secret
  namespace: default
type: Opaque
stringData:
  PROWLARR__APP__INSTANCENAME: "Prowlarr"
  PROWLARR__AUTH__APIKEY: "0ffa7873558e470d9510022a54d995e7"
