apiVersion: v1
kind: ConfigMap
metadata:
  name: decypharr-values
  namespace: default
data:
  values.yaml: |
    persistence:
      realdebrid:
        enabled: false
        type: persistentVolumeClaim
        existingClaim: realdebrid-webdav
        globalMounts:
          - path: /storage/realdebrid
