---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: decypharr
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: decypharr
      version: "0.2.0"
      sourceRef:
        kind: HelmRepository
        name: chillincool
        namespace: flux-system
  install:
    remediation:
      retries: 3
    createNamespace: false
    crds: Create
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
  values:
    controllers:
      main:
        initContainers:
          create-directories:
            image: alpine:latest
            command:
              - sh
              - -c
              - |
                mkdir -p /storage/realdebrid
                mkdir -p /storage/symlinks/downloads/sonarr
                mkdir -p /storage/symlinks/downloads/sonarr4k
                mkdir -p /storage/symlinks/downloads/radarr
                mkdir -p /storage/symlinks/downloads/radarr4k
                mkdir -p /storage/symlinks/movies
                mkdir -p /storage/symlinks/movies-4k
                mkdir -p /storage/symlinks/series
                mkdir -p /storage/symlinks/series-4k
                mkdir -p /storage/symlinks/series-anime
                chown -R 568:568 /storage
            volumeMounts:
              - name: realdebrid
                mountPath: /storage/realdebrid
              - name: symlinks
                mountPath: /storage/symlinks
    
    service:
      type: NodePort
      port: 8282
      nodePort: 30828
      targetPort: http
    
    podSecurityContext:
      fsGroup: 568
    
    securityContext:
      runAsNonRoot: false
      runAsUser: 568
      runAsGroup: 568
      readOnlyRootFilesystem: false
    
    valuesFrom:
      - kind: ConfigMap
        name: decypharr-values

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: shared-app-config
        globalMounts:
          - path: /config
            subPath: decypharr
      realdebrid:
        enabled: false
        type: persistentVolumeClaim
        existingClaim: realdebrid-webdav
        globalMounts:
          - path: /storage/realdebrid
      symlinks:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: symlinks
        globalMounts:
          - path: /storage/symlinks
