---
- id: radarr-pushover
  execute-command: /config/radarr-pushover.sh
  pass-arguments-to-command:
    - source: entire-payload

- id: seerr-pushover
  execute-command: /config/seerr-pushover.sh
  pass-arguments-to-command:
    - source: entire-payload

- id: sonarr-pushover
  execute-command: /config/sonarr-pushover.sh
  pass-arguments-to-command:
    - source: entire-payload

- id: plex-discord
  execute-command: /config/plex-discord.sh
  parse-parameters-as-json:
    - source: payload
      name: payload
  pass-arguments-to-command:
    - source: payload
      name: payload
