---
# yaml-language-server: $schema=https://kubernetes-schemas-cvg.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless-ngx
spec:
  components:
    # - ../../../../components/nfs-scaler
    - ../../../../components/volsync
  dependsOn:
    - name: cloudnative-pg
      namespace: cloudnative-pg
    - name: longhorn
      namespace: longhorn-system
  interval: 1h
  path: ./kubernetes/apps/util/paperless-ngx/app
  postBuild:
    substitute:
      APP: paperless-ngx
      VOLSYNC_CAPACITY: 5Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: util
  wait: false
