---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmagent-kubelet-metrics
rules:
  - apiGroups: [""]
    resources:
      - nodes/metrics
      - nodes/proxy
    verbs: ["get", "list"]
  - nonResourceURLs:
      - /metrics
      - /metrics/cadvisor
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vmagent-kubelet-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vmagent-kubelet-metrics
subjects:
  - kind: ServiceAccount
    name: vmagent-vmagent
    namespace: monitoring
