---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: oauth2-proxy
spec:
  interval: 30m
  path: ./kubernetes/apps/keycloak/oauth2-proxy/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  timeout: 5m
  targetNamespace: keycloak
  dependsOn:
    - name: cert-manager
    - name: keycloak
