---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: decypharr-tls
  namespace: media
spec:
  secretName: decypharr-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - decypharr.chillincool.net

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: huntarr-tls
  namespace: media
spec:
  secretName: huntarr-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - huntarr.chillincool.net

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lidarr-tls
  namespace: media
spec:
  secretName: lidarr-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - lidarr.chillincool.net

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: overseerr-tls
  namespace: media
spec:
  secretName: overseerr-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - overseerr.chillincool.net

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex-tls
  namespace: media
spec:
  secretName: plex-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - plex.chillincool.net

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prowlarr-tls
  namespace: media
spec:
  secretName: prowlarr-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - prowlarr.chillincool.net

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr-tls
  namespace: media
spec:
  secretName: radarr-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - radarr.chillincool.net

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr-4k-tls
  namespace: media
spec:
  secretName: radarr-4k-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - radarr-4k.chillincool.net

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarr-tls
  namespace: media
spec:
  secretName: sonarr-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - sonarr.chillincool.net

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarr-4k-tls
  namespace: media
spec:
  secretName: sonarr-4k-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - sonarr-4k.chillincool.net

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarr-anime-tls
  namespace: media
spec:
  secretName: sonarr-anime-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - sonarr-anime.chillincool.net

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: suggestarr-tls
  namespace: media
spec:
  secretName: suggestarr-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - suggestarr.chillincool.net

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tautulli-tls
  namespace: media
spec:
  secretName: tautulli-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - tautulli.chillincool.net
