---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tautulli-test-tls
  namespace: media
spec:
  secretName: tautulli-test-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - tautulli.test.chillincool.net
