---
# Allow istio-gateway-internal in network namespace to reference TLS secrets in media namespace
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: media-to-network
  namespace: media
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: network
  to:
    - group: ""
      kind: Secret
      name: decypharr-tls
    - group: ""
      kind: Secret
      name: huntarr-tls
    - group: ""
      kind: Secret
      name: lidarr-tls
    - group: ""
      kind: Secret
      name: overseerr-tls
    - group: ""
      kind: Secret
      name: plex-tls
    - group: ""
      kind: Secret
      name: prowlarr-tls
    - group: ""
      kind: Secret
      name: radarr-tls
    - group: ""
      kind: Secret
      name: radarr-4k-tls
    - group: ""
      kind: Secret
      name: sonarr-tls
    - group: ""
      kind: Secret
      name: sonarr-4k-tls
    - group: ""
      kind: Secret
      name: sonarr-anime-tls
    - group: ""
      kind: Secret
      name: suggestarr-tls
    - group: ""
      kind: Secret
      name: tautulli-tls
