---
# Allow istio-gateway-internal in network namespace to reference TLS secrets in media namespace
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: media-to-network
  namespace: media
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: istio-gateway-internal
      namespace: network
  to:
    - group: ""
      kind: Secret
