---
# yaml-language-server: $schema=https://kubernetes-schemas-cvg.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: qui-secret
    template:
      data:
        QUI__SESSION_SECRET: "{{ .QUI_SESSION_SECRET }}"
        QUI__OIDC_CLIENT_SECRET: "{{ .QUI_OIDC_CLIENT_SECRET }}"
        WRTAG_API_KEY: "{{ .WRTAG_API_KEY }}"
  dataFrom:
    - extract:
        key: qui
