---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./helmrepository-1password.yaml
  - ./helmrepository-cert-manager.yaml
  - ./helmrepository-chillincool.yaml
  - ./helmrepository-cilium.yaml
  - ./helmrepository-grafana.yaml
  - ./helmrepository-istio.yaml
  - ./helmrepository-kiali.yaml
  - ./helmrepository-longhorn.yaml
  - ./helmrepository-prometheus-community.yaml
  - ./helmrepository-stakater.yaml
  - ./helmrepository-victoria-metrics.yaml
  - ./ks-onepassword-connect.yaml
  - ./ks-infrastructure-apps.yaml
  - ./ks-kube-system-apps.yaml
  - ./ks-media-apps.yaml
  - ./ks-monitoring-apps.yaml
