---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./helmrepository-cert-manager.yaml
  - ./helmrepository-envoy-gateway.yaml
  - ./helmrepository-chillincool.yaml
  - ./helmrepository-cilium.yaml
  - ./helmrepository-longhorn.yaml
  - ./helmrepository-stakater.yaml
  - ./ks-cert-manager.yaml
  - ./ks-cert-manager-issuers.yaml
  - ./ks-default-apps.yaml
  - ./ks-kube-system-apps.yaml
  - ./ks-storage-apps.yaml
