---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ./namespace.yaml
  - ./helmrepository-chillincool.yaml
  - ./helmrepository-democratic-csi.yaml
  - ./ks-default-apps.yaml
  - ./ks-storage-apps.yaml
