---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  # - ./helmrepository-1password.yaml
  - ./helmrepository-bitnami.yaml
  - ./helmrepository-cert-manager.yaml
  - ./helmrepository-chillincool.yaml
  - ./helmrepository-cilium.yaml
  - ./helmrepository-cloudnative-pg.yaml
  - ./helmrepository-csi-driver-nfs.yaml
  - ./helmrepository-hashicorp.yaml
  - ./helmrepository-istio.yaml
  - ./helmrepository-jp-gouin.yaml
  - ./helmrepository-longhorn.yaml
  - ./helmrepository-oauth2-proxy.yaml
  - ./helmrepository-stakater.yaml
  - ./ks-external-secrets-apps.yaml
  - ./ks-infrastructure-apps.yaml
  - ./ks-keycloak-apps.yaml
  - ./ks-kube-system-apps.yaml
  - ./ks-media-apps.yaml
  - ./ks-network-apps.yaml
  - ./ks-observability-apps.yaml
  - ./ks-storage-apps.yaml
  - ./ks-openebs-system.yaml
  - ./ks-volsync-system.yaml
