apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: decypharr-enable
  namespace: flux-system
spec:
  interval: 1m
  path: ./kubernetes/apps/media/decypharr/enable
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: decypharr
  wait: true
  timeout: 5m
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: decypharr-webdav-controller
      namespace: media
  targetNamespace: media
