apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: decypharr-enable
  namespace: flux-system
spec:
  interval: 1m
  path: ./kubernetes/apps/default/decypharr/enable
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: decypharr
  wait: true
  timeout: 5m
  healthChecks:
    - apiVersion: batch/v1
      kind: Job
      name: decypharr-webdav-readiness-gate
      namespace: default
  targetNamespace: default
