---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trust-manager-bundle
  namespace: flux-system
spec:
  dependsOn:
    - name: trust-manager
  interval: 30m
  path: ./kubernetes/apps/infrastructure/trust-manager/bundle
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m
