---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-metrics-k8s-stack
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/apps/monitoring/victoria-metrics-k8s-stack/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 15m
  targetNamespace: monitoring
