---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kiali-cr
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/apps/monitoring/kiali-operator/resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 10m
  targetNamespace: kiali-operator
  dependsOn:
    - name: kiali-operator
