---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/wunderio/csi-rclone/master/deploy/kubernetes/1.20/csi-nodeplugin-rclone.yaml
  - https://raw.githubusercontent.com/wunderio/csi-rclone/master/deploy/kubernetes/1.20/csi-controller-rclone.yaml
  - ./rclone-secret.yaml
  - ./storageclass.yaml
