---
apiVersion: v1
kind: Secret
metadata:
  name: rclone-secret
  namespace: kube-system
type: Opaque
stringData:
  remote: decypharr
  remotePath: /realdebrid
  configData: |
    [decypharr]
    type = webdav
    url = http://decypharr.media.svc.cluster.local:8282/webdav
    vendor = other
