---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rclone-realdebrid
provisioner: rclone.csi.veloxpack.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  csi.storage.k8s.io/provisioner-secret-name: rclone-secret-realdebrid
  csi.storage.k8s.io/provisioner-secret-namespace: csi-rclone
  csi.storage.k8s.io/controller-publish-secret-name: rclone-secret-realdebrid
  csi.storage.k8s.io/controller-publish-secret-namespace: csi-rclone
  csi.storage.k8s.io/node-stage-secret-name: rclone-secret-realdebrid
  csi.storage.k8s.io/node-stage-secret-namespace: csi-rclone
  csi.storage.k8s.io/node-publish-secret-name: rclone-secret-realdebrid
  csi.storage.k8s.io/node-publish-secret-namespace: csi-rclone
  remote: decypharr
  remotePath: /realdebrid
