---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-referencegrant
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/apps/infrastructure/envoy-gateway/referencegrant
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: envoy-gateway-config
  wait: true
  timeout: 5m
  targetNamespace: media
