---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-root-ca
  namespace: cert-manager
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFxzCCA6+gAwIBAgIUK9S1WjBDGRJQdEgGF98jeSSI4b4wDQYJKoZIhvcNAQEL
    BQAwNDEUMBIGA1UEChMLY2hpbGxpbmNvb2wxHDAaBgNVBAMTE0NoaWxsaW5jb29s
    IFJvb3QgQ0EwHhcNMjYwMTAzMjAwNjIzWhcNMzYwMTAxMjAwNjQ1WjA0MRQwEgYD
    VQQKEwtjaGlsbGluY29vbDEcMBoGA1UEAxMTQ2hpbGxpbmNvb2wgUm9vdCBDQTCC
    AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAMnjTAS1tXdIRU1QCzp2xmaS
    n1pWJW8FA2aL/wAthw1/gAAh0XmQzO3LW4vlwWi3RQj6UHmZ2SgTlT1Ro5z1w2gB
    1a+s6SDCxj2j9mAAc3GkVDUnp3t2/DFW2FADXwfQzYzPpFjYNQMrbM8Ni1yFeV6A
    2qfSMuoB/oWdGHG06jaqOzKoNWWmqoGbrTGhbUS5mOGRAY5hrg5QGhBxialySOc1
    SHNM4Uugf/BAHG7nRiPH1b+SRC34nj+p7wrU3EpdjqkeVScxv3duvM65zJ6MWOMA
    +FQG68HT3Y+8y8gY4c3JkARGu/4pgw8Hto3lWc/mxy2ki4EeSwGUe64wWHfi4rsr
    pMDwaRznoVhys+fuRJxhdmfDs93ihOEtUH6kWxSglYPKTB+RPcLRMPXNUnTAdNZl
    doAfXDimnTsesio7bkkCoEEXDUeuLFnqKHIUwGhrklmMmW4CdOedfEBqo6zUKu80
    meks4ZSrdKIO4J2xzx9Q7A8DEqS7TBt4NOoAixRmjSMCZklyoHX7pNQCXKVc7BUN
    d+7Sel70rc4GbCEJTcthEdeinDyWyA8L+Zw94s82+R2PvWYzbM4TIs8+8PyaQHA+
    yrgwydmtmiZf48CBsyWakRJozik7Lgo1yIH/f1AQNALmv+Co1lzYbOO/FDhmSaFq
    zK5UA/ZuWESM5aOvExALAgMBAAGjgdAwgc0wDgYDVR0PAQH/BAQDAgEGMA8GA1Ud
    EwEB/wQFMAMBAf8wHQYDVR0OBBYEFFHhHl9YT26hCTtnjDbW1tXfNkmrMB8GA1Ud
    IwQYMBaAFFHhHl9YT26hCTtnjDbW1tXfNkmrMDkGCCsGAQUFBwEBBC0wKzApBggr
    BgEFBQcwAoYdaHR0cHM6Ly92YXVsdC5sb2NhbC92MS9wa2kvY2EwLwYDVR0fBCgw
    JjAkoCKgIIYeaHR0cHM6Ly92YXVsdC5sb2NhbC92MS9wa2kvY3JsMA0GCSqGSIb3
    DQEBCwUAA4ICAQCGU0kNNTEvHr5CJCtAh8HWSBvDUTbTRyN+Tc+bz+zL3B15ghQl
    jb805/BFYmsa0v854uuc6jIiPC+4CMEaH92B1HZQKQMSk9XIaBmF98cXTSPPioD3
    jlGSl/Oj/XQtrXDI8ESnbGnCu7ovP/0z6yygrl4DbUbvHHch+/+lJP9q+FFcdI9+
    D35oAkrrGzISo9t2EVEXBhUxYZoUciYyga0QlJVrkEbd8zhXKOFHLpcKF60o3m9q
    1MiYXTniMQraZU6VFJN9mRCX48DC43t5UT5OH7BgiEf24Yb7jBkwg61vCIt7HiGG
    NQ5pJOWQ2LZmbO0sQ5AHckgpqdMHwkNBog/lx7UDMWk1s/VbN0RUoG74IiwcTrit
    VPwXQFpAx7sN56q1NtDpknje01f5Vv87DRJoNR7wUSse4a/ZPvJlQPBfNazWbJ3i
    4k6zmhOTEESeCErt5TN+DsMZKsuN9tFS5B3uZK2xwYhdoDRplmv6Ap6ajLVuYyIY
    Sp/FMDXus4PRqfslgyo1E7PNyCW6s3BOi/Q3BfhVKQOUX0CIMISi4aR9D5cFcVQW
    tRpAQmhfhKF/zcC7z+HE3N6YTwhSAUgYvwSs8a1hQrW+1gmELRBaqh2fADglTG7l
    e+GNhiyegzAa5v+aO7ObiTKYk7dOHWE0V/lvMAaXJlAAiwrWspV6tKeY9w==
    -----END CERTIFICATE-----
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: vault-ca-bundle
spec:
  sources:
    - configMap:
        name: vault-root-ca
        key: ca.crt
  target:
    configMap:
      key: ca.crt
