apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: keycloak-operator
  namespace: flux-system
spec:
  interval: 1h
  resources:
    - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.4.7/kubernetes/kubernetes.yml
  prune: true
  dependsOn:
    - name: keycloak-crds
  wait: true
