apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 1h
  prune: true
  wait: true
  resources:
    - ../namespace.yaml
    - ./kustomization-crds.yaml
    - ./kustomization-operator.yaml
    - ./kustomization-instance.yaml