apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: keycloak-instance
  namespace: flux-system
spec:
  interval: 1h
  resources:
    - https://raw.githubusercontent.com/your-org/flux-repo/main/keycloak/keycloak-instance.yml
  dependsOn:
    - name: keycloak-operator
    - name: keycloak-crds
  prune: true

