---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - crds-remote
  - operator-remote
  - postgres.yaml
  - certificate.yaml
  - ldap-client-certificate.yaml
  - keycloak.yaml
  - gateway.yaml
