apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: keycloak-crds
  namespace: flux-system
spec:
  interval: 1h
  prune: true
  wait: true
  timeout: 10m
  resources:
    # Keycloak CRD
    - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.4.7/kubernetes/keycloaks.k8s.keycloak.org-v1.yml
    # KeycloakRealmImport CRD
    - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.4.7/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml
