---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - crds.yaml
  - operator-remote
  - postgres.yaml
  - certificate.yaml
  - keycloak.yaml
  - gateway.yaml
