---
# yaml-language-server: $schema=https://kubernetes-schemas-cvg.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich
spec:
  components:
    - ../../../components/volsync
  dependsOn:
    - name: cloudnative-pg
      namespace: cloudnative-pg
    - name: longhorn
      namespace: longhorn-system
  interval: 1h
  path: ./kubernetes/apps/util/immich/app
  postBuild:
    substitute:
      APP: immich
      VOLSYNC_CAPACITY: 10Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: util
  wait: false
