---
# yaml-language-server: $schema=https://kubernetes-schemas-cvg.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: navidrome
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: navidrome-secret
    template:
      data:
        ND_LASTFM_APIKEY: "{{ .LASTFM_API_KEY }}"
        ND_LASTFM_SECRET: "{{ .LASTFM_SHARED_SECRET }}"
  dataFrom:
    - extract:
        key: navidrome
---
# yaml-language-server: $schema=https://kubernetes-schemas-cvg.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: navidrome-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: navidrome-oidc-secret
    template:
      data:
        client-secret: "{{ .NAVIDROME_OIDC_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: navidrome
