---
# yaml-language-server: $schema=https://kubernetes-schemas-cvg.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2-3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 5Gi
    storageClass: longhorn
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-db-secret
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 512Mi
  backup:
    barmanObjectStore:
      serverName: keycloak-db-restored
      destinationPath: s3://keycloak-db
      endpointURL: https://80035b568c77008106a1c2320cb9b69d.r2.cloudflarestorage.com
      s3Credentials:
        accessKeyId:
          name: cloudflare-r2-secret
          key: R2_ACCESS_KEY_ID
        secretAccessKey:
          name: cloudflare-r2-secret
          key: R2_SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "30d"
