---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-crds
  namespace: keycloak
data:
  placeholder: "CRDs will be fetched from remote"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-crds
  namespace: flux-system
spec:
  interval: 1h
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/infrastructure/keycloak/app/crds-remote
