---
# yaml-language-server: $schema=https://kubernetes-schemas-cvg.pages.dev/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: keycloak-db
spec:
  schedule: "0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: keycloak-db
