---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ldap-account-manager
  namespace: openldap
spec:
  parentRefs:
    - name: openldap-gateway-istio
      namespace: openldap
  hostnames:
    - lam.chillincool.net
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ldap-account-manager
          port: 80
