---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../namespace.yaml
  - ../cert-manager-rbac.yaml
  - ../onepassworditem.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./phpldapadmin.yaml
  - ../istio-gateway/gateway.yaml
  - ../istio-gateway/certificates.yaml
