---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sonarr-anime
  namespace: default
spec:
  parentRefs:
    - name: main-gateway
      namespace: default
      sectionName: https-sonarr-anime
  hostnames:
    - "sonarr-anime.chillincool.net"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: sonarr-anime
          port: 8989
