---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak
spec:
  dependsOn:
    - name: cloudnative-pg
      namespace: cloudnative-pg
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: keycloak
      namespace: keycloak
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: keycloak-db
      namespace: keycloak
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      failed: status.phase == 'Failed'
      current: status.phase == 'Cluster in healthy state'
  interval: 1h
  path: ./kubernetes/apps/keycloak/keycloak/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: keycloak
