---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: monitoring
spec:
  secretName: grafana-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - grafana.chillincool.net

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kiali-tls
  namespace: monitoring
spec:
  secretName: kiali-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - kiali.chillincool.net
