---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-gateway-istio
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/apps/monitoring/istio-gateway
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 10m
  targetNamespace: monitoring
