---
# yaml-language-server: $schema=https://kubernetes-schemas-cvg.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: immich-db-secret
    template:
      data:
        username: immich
        password: "{{ .POSTGRES_PASSWORD }}"
  dataFrom:
    - extract:
        key: immich
---
# yaml-language-server: $schema=https://kubernetes-schemas-cvg.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-r2
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: immich-r2-secret
    template:
      data:
        R2_ACCESS_KEY_ID: "{{ .R2_ACCESS_KEY_ID }}"
        R2_SECRET_ACCESS_KEY: "{{ .R2_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: immich
